config/routes.rb
Kontakt::Application.routes.draw do
  resources :konts
  root :to => "konts#index"
end

app/models/kont.rb
class Kont < ActiveRecord::Base
  attr_accessible :imie, :nazwisko, :stanowisko, :telefon1, :telefon2, :mail, :miasto

  validates_presence_of :imie, :presence => true 
  validates_length_of :imie, :in => 3..10
  validates_presence_of :nazwisko, :presence => true
  validates_length_of :nazwisko, :in => 3..10
  validates_presence_of :stanowisko, :presence => true
  validates_length_of :stanowisko, :in => 3..50
  validates_presence_of :telefon1, :presence => true
  validates_length_of :telefon1, :is => 9

  validates_length_of :telefon2, :is => 9, :allow_blank => true
  validates_presence_of:mail, :presence => true
  validates_uniqueness_of :mail
  validates_presence_of :miasto, :presence => true

  def self.search(search)
  	if search
   	where('imie LIKE ? or nazwisko LIKE ? or stanowisko LIKE ? or telefon1 LIKE ? or telefon2 LIKE ? or miasto LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        else
  	  scoped
        end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/konts_helper.rb
module KontsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/konts/_form.html.erb
<%= form_for @kont do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :imie %><br />
    <%= f.text_field :imie %>
  </p>
  <p>
    <%= f.label :nazwisko %><br />
    <%= f.text_field :nazwisko %>
  </p>
  <p>
    <%= f.label :stanowisko %><br />
    <%= f.text_field :stanowisko %>
  </p>
  <p>
    <%= f.label :telefon1 %><br />
    <%= f.text_field :telefon1 %>
  </p>
  <p>
    <%= f.label :telefon2 %><br />
    <%= f.text_field :telefon2 %>
  </p>
  <p>
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </p>
  <p>
    <%= f.label :miasto %><br />
    <%= f.text_field :miasto %>
  </p>
  <p>
  <%= f.submit :Zatwierdź %>
  </p>
<% end %>

app/views/konts/edit.html.erb
<% title "Edit Kont" %>

<%= render 'form' %>

<p>
  <%= link_to "Pokaż", @kont %> |
  <%= link_to "Pokaż listę", konts_path %>
</p>

app/views/konts/index.html.erb
<% title "Konts" %>

<table cellspacing="20">
  <tr>
    <th style="text-align: left">Imię</th>
    <th style="text-align: left">Nazwisko</th>
    <th style="text-align: left">Stanowisko</th>
   
  </tr>
  <% for kont in @konts %>
    <tr>
      <td><%= kont.imie %></td>
      <td><%= kont.nazwisko %></td>
      <td><%= kont.stanowisko %></td>
     
      <td style="text-align: right"><%= link_to "Pokaż", kont %></td>
    </tr>
  <% end %>
</table>


<p><%= paginate @konts %></p>
<p style="text-align: right; font-size: 14px; font-weight: bold; margin: 2em 0;"><%= link_to "Dodaj kontakt", new_kont_path %></p>

<%= form_tag konts_path, :method => :get, :id => "konts_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/konts/new.html.erb
<% title "New Kont" %>

<%= render 'form' %>


<p><%= link_to "Pokaż listę", konts_path %></p>

app/views/konts/show.html.erb
<% title "Kont" %>

<p>
  <strong>Imię:</strong>
  <%= @kont.imie %>
</p>
<p>
  <strong>Nazwisko:</strong>
  <%= @kont.nazwisko %>
</p>
<p>
  <strong>Stanowisko:</strong>
  <%= @kont.stanowisko %>
</p>
<p>
  <strong>Telefon1:</strong>
  <%= @kont.telefon1 %>
</p>
<p>
  <strong>Telefon2:</strong>
  <%= @kont.telefon2 %>
</p>
<p>
  <strong>Mail:</strong>
  <%= @kont.mail %>
</p>
<p>
  <strong>Miasto:</strong>
  <%= @kont.miasto %>
</p>

<p>
  <%= link_to "Edycja", edit_kont_path(@kont) %> |
  <%= link_to "Usuń", @kont, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Pokaż listę", konts_path %>
</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pl">
<head>
	<title>Kontakty</title>
	<%= stylesheet_link_tag :all %>  
 	<%= javascript_include_tag :defaults %>  
 	<%= csrf_meta_tag %>  
 	<meta charset="utf-8" />
 	
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

	<header>
		<h1>Książka telefoniczna</h1>
	</header>
	<nav>
		<ul>
			<li class="selected"><a href="/"<%= I18n.t('site.title') %>>Strona Główna</a></li>
			<li><a href="http://www.bomi.pl/">Bomi.pl</a></li>
			<li><a href="http://www.siec34.pl/">Sieć 34</a></li>
			<li><a href="http://www.rabatpomorze.pl/">Rabat Service</a></li>
			
			
		</ul>
	</nav>
	<section id="intro">
		<header>
			<h2>Książka Telefoniczna Firmy</h2>
		</header>
		<p>Cudowna książka napisana przez Iwonkę</p>
		<img src="../../../images/introimage.png" alt="lime" />
	</section>
	
	<div id="innercontent">
				<article class="articlecontent">
				<header>
					<img src="../../../images/logo1.jpg" alt="" class="alignright" />
						<h2>Kontakty</h2>
					</header>
					<p><div id="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1 %>
      <%= yield %>
      </div></p>
				</article>
			</div>

		
		<aside>
			<section>
				<header>
					<h3>Portale</h3>
				</header>
				<ul>
					<li><a href="http://www.wiadomoscihandlowe.com.pl/">Wiadomości Handlowe</a></li>
					<li><a href="http://www.dlahandlu.pl/">DlaHandlu.pl</a></li>
					<li><a href="http://www.bestshopnet.pl/Strona-glowna.aspx">BestShopNet</a></li>
					<li><a href="http://www.pb.pl/">Puls Biznesu</a></li>
					<li><a href="http://www.parkiet.com/">Parkiet</a></li>
				</ul>
			</section>
			
			<section>
				<header>
					<h3>Produkty</h3>
				</header>
					<img src="../../../images/2-thumb.jpg" alt="przerwa" /> <img src="../../../images/6-thumb.jpg" alt="kawka" />
					<br />
					<img src="../../../images/1-thumb.jpg" alt="odpoczynek" /> <img src="../../../images/7-thumb.jpg" alt="wytchnienie" />
					<br /><br />
			</section>
			

<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>